CREATE TABLE products (
Id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
short_desc TEXT NOT NULL,
description TEXT NOT NULL,
price NUMERIC(10,2) NOT NULL,
created TIMESTAMP NOT NULL DEFAULT NOW(),
updated TIMESTAMP NOT NULL DEFAULT NOW()
);